name: Test Action
on:
  push:
    branches: ["main"]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo hola mundo
      - name: Checkout
        uses: actions/checkout@v4
